### ISSUE TITLE
ModuleNotFoundError: No module named 'hrseg.hrseg_lib.datasets.cityscapes'

### ISSUE THREAD

**Issue by DreannER** [langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement#10]
ModuleNotFoundError: No module named 'hrseg.hrseg_lib.datasets.cityscapes'，what's the problem,how can i solva this?ths

**Comment by HibobacX** [comment]
I just ran a test, this line of code is useless during the test, I commented it out, it does not affect the results, but I did not try the training, this needs you to according to the specific situation
![Snipaste_2023-07-19_21-14-06](https://github.com/langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement/assets/129464736/2ee2e6b4-77d8-49ce-8af2-5bf11da9970f)

**Comment by liuQan** [comment]
hi  I encounter the same problem in train  ,and ,have you solved the problem???
