### ISSUE TITLE
Fine tune the result

### ISSUE THREAD

**Issue by FireWallDragonDarkFluid** [langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement#11]
Hi!
From the code [here](https://github.com/langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement/blob/a21fae9b1ce2923582a1dfdd5a918af0536ad210/LLFlow_SKF/code/test.py#L155)

You fine tune the result by using the test data, am I correct?

Which is a serious problem and unfair way to evaluate your model, will you rerun the code by modify the test.py file?
I assume there will be a huge different results compare to the orignals.

**Comment by langmanbusi** [comment]
We use the same way as LLFlow to conduct the comparison, please refer to https://github.com/wyf0912/LLFlow/blob/f5ad48719285be2bc945ebccf8ad2338cad887f6/code/test.py#L144
