### ISSUE TITLE
Runtimes

### ISSUE THREAD

**Issue by kkllww** [langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement#13]
May I ask what is the inference time for your model when processing images of different sizes? Can it achieve real-time processing

**Comment by langmanbusi** [comment]
Sorry about that we didn't compare the runtime. Actually, the runtime of our method is based on the runtime of each baseline. If the baseline method could achieve real-time processing, the baseline-SKF may achieve the same performance. But the extra processing time brought by segmentation model may make it slower, which is a shortcoming of our work. Hope you could propose better method ^_^
