### ISSUE TITLE
how can i solve the problem of   File "/home/liuqiang/anaconda3/doc/SNR_SKF/models/hrseg_model.py", line 13, in <module>     from .hrseg_lib.datasets.cityscapes import Cityscapes ModuleNotFoundError: No module named 'models.hrseg_lib.datasets.cityscapes'

### ISSUE THREAD

**Issue by liuQan** [langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement#14]
![4%Z( YR$LVZLU %R)V ~_I4](https://github.com/langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement/assets/125167883/96e4507c-0b5e-45e8-8325-a2c860b999c5)

**Comment by langmanbusi** [comment]
Sorry, we forgot to delete this useless code, just comment or delete it. 
If you would like to switch the segmentation model pre-trained on other datasets, you can import other files.
FYI, you can find the file here https://github.com/HRNet/HRNet-Semantic-Segmentation/tree/0bbb2880446ddff2d78f8dd7e8c4c610151d5a51/lib/datasets
