### ISSUE TITLE
problems of training LLFlow_SKF

### ISSUE THREAD

**Issue by RenJiahuan** [langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement#2]
some errors in folder  /LLFlow_SKF/code/hrseg/hrseg_lib/datasets/__init__.py
ModuleNotFoundError: No module named 'hrseg.hrseg_lib.datasets.cityscapes'

**Comment by RenJiahuan** [comment]
solved

**Comment by RenJiahuan** [comment]
File "/LLFlow_SKF/code/hrseg/hrseg_lib/datasets/__init__.py", line 11, in <module>
    from .cityscapes import Cityscapes as cityscapes

**Comment by langmanbusi** [comment]
Just delete this import in init.py, only leave import of pascal_ctx
