### ISSUE TITLE
找不到模块

### ISSUE THREAD

**Issue by Lantanoi** [langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement#21]
作者您好，想问下Learning Semantic-Aware Knowledge Guidance for Low-Light Image Enhancement您这篇文章的代码是在哪里呢，我想看一下这篇论文中提出的semantic-aware embedding (SE) module可以吗？非常感谢

**Comment by langmanbusi** [comment]
感谢关注，代码中的变量名与论文的代指有所不同。。所有代码中，SEM都是用TransformerBlock或者TransformerBlock_1表示的

在SNR-SKF中，
引用在https://github.com/langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement/blob/a21fae9b1ce2923582a1dfdd5a918af0536ad210/SNR_SKF/models/archs/low_light_transformer_seg_128.py#L45
定义在https://github.com/langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement/blob/a21fae9b1ce2923582a1dfdd5a918af0536ad210/SNR_SKF/models/archs/Fuse_Block.py#L182

在LLFlow-SKF中，用了两种结构（TransformerBlock和TransformerBlock_1），不过也只是为了减小嵌入维度，输入层多了几个卷积，
代码中的TransformerBlock：
引用在https://github.com/langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement/blob/a21fae9b1ce2923582a1dfdd5a918af0536ad210/LLFlow_SKF/code/models/modules/LLFlow_pc_small_arch.py#L64
定义在https://github.com/langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement/blob/a21fae9b1ce2923582a1dfdd5a918af0536ad210/LLFlow_SKF/code/models/modules/Fuse_Block.py#L132
代码中的TransformerBlock_1：
引用在https://github.com/langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement/blob/a21fae9b1ce2923582a1dfdd5a918af0536ad210/LLFlow_SKF/code/models/modules/LLFlow_pc_small_arch.py#L72
定义在https://github.com/langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement/blob/a21fae9b1ce2923582a1dfdd5a918af0536ad210/LLFlow_SKF/code/models/modules/Fuse_Block.py#L156

在DRBN-SKF中
引用在https://github.com/langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement/blob/a21fae9b1ce2923582a1dfdd5a918af0536ad210/DRBN_SKF/src/model/drbn.py#L142
定义在https://github.com/langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement/blob/a21fae9b1ce2923582a1dfdd5a918af0536ad210/DRBN_SKF/src/model/Fuseblock.py#L133

定义其实都是一样的，为了方便您查找都给了出来。源代码是参考的[Restormer](https://github.com/swz30/Restormer)，没有做很多修改。

希望对您有帮助。

**Comment by Lantanoi** [comment]
好的，太感谢您了！
