### ISSUE TITLE
文件

### ISSUE THREAD

**Issue by chenhuimei55** [langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement#22]
作者你好，我想问一下这个文件在哪里torch.load('../checkpoints/LOLv2-DRBN-SKF/model_lol_v2.pt'，求求了求求了

**Comment by langmanbusi** [comment]
在Readme里写了的呀。。要下载一下。。
https://github.com/langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement/blob/a21fae9b1ce2923582a1dfdd5a918af0536ad210/DRBN_SKF/README.md?plain=1#L17
然后放在对应的目录下

**Comment by chenhuimei55** [comment]
好的，谢谢您啦
