### ISSUE TITLE
关于代码的问题

### ISSUE THREAD

**Issue by Wickedness230** [langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement#23]
作者您好，我在运行您的SNR-SKF这部分的代码，想请教一下，在 Video_base_model4_m.py 中，在初始化的时候为什么要load一个训练好的结果？

self.print_network()
self.load()

**Comment by langmanbusi** [comment]
你好，感谢关注，
这个地方可以不load，注释掉就行。。
我是因为资源有限，在调参改代码的时候为了快点出一个大概结果，用来load原模型的参数。你如果需要跑很多case study的话，也可以load一下试试

**Comment by Wickedness230** [comment]
感谢您的回复，想再请教几个问题。
我个人不太懂语义分割，想问一下，seg_map和 seg_feature 分别是什么？另外，加载的语义分割模型HRNet是原作者训练好的吗？

**Comment by langmanbusi** [comment]
seg_map是HRNet的语义分割结果，seg_feature是HRNet输出的不同尺度的特征图，这些特征图在HRNet最后的输出头之前合并，然后经过输出头得到seg_map。加载的HRNet是训练好的，这个在文中有写，关于语义分割也可以去看看HRNet原文，虽然实验部分不只是做语义分割，但是是一篇很经典的文章，写的很好。

**Comment by Wickedness230** [comment]
HRNet的参数不更新的是吧，另外训练时输入HRNet的是正常光照的图像？

**Comment by langmanbusi** [comment]
对，不更新。至于训练时的输入，每个baseline不太一样，像DRBN就是用前一个循环的输出，具体你可以看看代码
