### ISSUE TITLE
代码

### ISSUE THREAD

**Issue by chenhuimei55** [langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement#25]
您好，我想问一下这个输入的不应该是图像特征和语义特征嘛，为什么直接就是96，32两个数字呀。
 if seg:
            self.fuseblk_1 = TransformerBlock(96, 32)
            self.fuseblk_2 = TransformerBlock(48, 16)
            self.fuseblk_3 = TransformerBlock(59, 16)

**Comment by langmanbusi** [comment]
你好，
这里是模型class的init部分，模型需要用到的各网络层在这里定义，TransformerBlock在这里实例化定义为self.fuseblk，其中96和32是TransformerBlock的init参数，可以去对应的文件里详细看看
https://github.com/langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement/blob/a2ade551508ecc7ea48f56ee5e49f023ea534c77/DRBN_SKF/src/model/Fuseblock.py#L133
self.fuseblk的调用在forward函数里
https://github.com/langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement/blob/a2ade551508ecc7ea48f56ee5e49f023ea534c77/DRBN_SKF/src/model/drbn.py#L173
可以再多看看代码，熟悉一下定义和调用，祝好^^

**Comment by chenhuimei55** [comment]
谢谢您了
