### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by Lvht123** [langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement#26]
你好，我有看到snr-skf的train.py有一段代码：seg_map, seg_feature = seg_model(GT)。请问在train的过程中，也有把groud truth输入到hrnet进行分割得到语义信息的步骤吗？
还有一个问题：请问fuse_block中的MultiEmbedding模块就是论文中的SEM吗？我看了代码感觉和文章的结构有点出入，比如一些layernorm层没有在代码中体现。
本人代码水平较差，现在想尝试将SEM应用到自己的baseline里，还望大佬指教

**Comment by langmanbusi** [comment]
实际训练还是输入LQ到分割网络里的，当时也有尝试如果训练时分割GT作为训练数据会对结果有什么影响，上传的这个版本可能没改，后来发现还是用LQ训练比较好，毕竟inference的时候是LQ，LQ和GT的差距还是有的，不过可能采取一些训练策略来混合LQ和GT会有更好的结果。

可以参考一下[#21](https://github.com/langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement/issues/21)，SEM是代码中的各个TransformerBlock

**Comment by Lvht123** [comment]
明白了，感谢大佬
