### ISSUE TITLE
loss问题

### ISSUE THREAD

**Issue by Lvht123** [langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement#27]
大佬，还想再请教一个问题。最后总的loss有三个子loss，请问其中两个权重参数在实验室设置为了多少？我在论文中没有找到

**Comment by langmanbusi** [comment]
可以看看代码里面具体怎么设置的，我也记不太清了。。在loss那里应该挺好找的
比如SNR是在这里
https://github.com/langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement/blob/a2ade551508ecc7ea48f56ee5e49f023ea534c77/SNR_SKF/models/Video_base_model4_m.py#L162

**Comment by Lvht123** [comment]
你好，我看到代码里hist_loss的权重在SNR_SKF和LLFlow_SKF分别是10000和1000，我目前在baseline上跑了10000的，感觉这个比例效果一般。请问你们在实验中设置的比例相差也这么大吗？
