### ISSUE TITLE
损失问题

### ISSUE THREAD

**Issue by Yy4441867** [langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement#28]
你好 我想请教一下 DRBN_SKF中，ssim损失为什么是负数，以及训练过程中的日志在哪里看，谢谢作者！

**Comment by ProudQin** [comment]
gpt





------------------ 原始邮件 ------------------
发件人: Yy4441867 ***@***.***&gt;
发送时间: 2024年4月22日 21:18
收件人: langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement] 损失问题 (Issue #28)





 
你好 我想请教一下 DRBN_SKF中，ssim损失为什么是负数，以及训练过程中的日志在哪里看，谢谢作者！

**Comment by langmanbusi** [comment]
你好，SSIM作为损失函数时要取负数，因为SSIM越大越好，而优化损失是一个最小化的过程。
日志在experiment文件夹里，
<img width="310" alt="image" src="https://github.com/langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement/assets/89068081/ab8b6d7d-05cc-4001-a24d-a5a6c3cfcf12">

**Comment by Yy4441867** [comment]
非常感谢您的指导 祝您工作顺利！
