### ISSUE TITLE
Error at calculate_loss_G

### ISSUE THREAD

**Issue by zyy317077** [langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement#3]
Dear author,
 Error at calculate_loss_G  in line 179 of the file DRBN_SKF/trainer_seg_hist_fuse.py, Is the input model_D correct here？
I would greatly appreciate it if you could provide me with an answer

**Comment by langmanbusi** [comment]
As shown in GAN, loss_G (update generator) and loss_D (update discriminator) are both calculated by discriminator (model_D), only the objective functions are different.

**Comment by zyy317077** [comment]
Thank you for your answer!
However, fake_label = model_D(torch.cat([out, seg_map])) in line 451 of  D_Net.py,  concating both dimension 0 and dimension 1 will result in errors.
How should I modify it?

**Comment by langmanbusi** [comment]
I update the code and you can check it.

**Comment by zyy317077** [comment]
Thank you once again！
