### ISSUE TITLE
ModuleNotFoundError: No module named 'hrseg.hrseg_lib.datasets.cityscapes'

### ISSUE THREAD

**Issue by qiyuebobo** [langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement#30]
作者你好：我目前遇到了如标题所示报错，根据查找是    from hrseg.hrseg_lib.datasets.cityscapes import Cityscapes没有相关文件，请问这应该要怎么解决？
另外，当我打开的根目录是LLFlow_SKF和DRBN_SKF，都出现了类似的情况：代码中有较多的import都处于标红状态（如下所示） ，想请您解答一下这是正常现象嘛？谢谢您~
![image](https://github.com/langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement/assets/76613430/ea176829-978f-4a1e-bb4b-57eb7093706d)
![image](https://github.com/langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement/assets/76613430/6778eff3-49ac-40b8-a7eb-c59c4a97bd2f)

**Comment by langmanbusi** [comment]
Please refer to https://github.com/langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement/issues/14#issuecomment-1685537141
