### ISSUE TITLE
请问可以用于非配对训练吗

### ISSUE THREAD

**Issue by Maozhiquan** [langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement#31]
大佬作者您好，请问您这篇优秀的工作可以用于非配对训练吗？另外您可以给出一点点关于配对训练的建议吗（一点点也行），非常非常非常感谢，祝您事业生活顺利！！！！

**Comment by langmanbusi** [comment]
非配对的话就只用SA loss就行

**Comment by Maozhiquan** [comment]
非常感谢作者百忙之中回了我，我想请问如果是用于非配对 亮度提升可以如此之大吗？因为我觉得非配对没有对应高亮图片做参考会学习不好，小白很好奇亮度提升的问题，如果作者大大还能看看我那就真的太感谢了
！！！

> 非配对的话就只用SA loss就行

**Comment by langmanbusi** [comment]
非配对的话亮度提升的话也不一定就会不好呀，低亮度和高亮度图像不同的概率分布还是能学习到的，基于GAN的方法也有很多效果不错的。有很多开源无监督方法可以参考，比如EnlightenGAN这些，不过损失函数的权重以及学习率可能要调一调，不然容易崩。

**Comment by Maozhiquan** [comment]
> 非配对的话亮度提升的话也不一定就会不好呀，低亮度和高亮度图像不同的概率分布还是能学习到的，基于GAN的方法也有很多效果不错的。有很多开源无监督方法可以参考，比如EnlightenGAN这些，不过损失函数的权重以及学习率可能要调一调，不然容易崩。

太谢谢您了！！！事实上我参考了EnlightenGAN这个，除了他论文结构的unet生成器没有参考（因为我做的是高清图像，所以unet很吃显卡没办法实现跑），其余都参考了并且调整成一样的，可是亮度几乎无改变，这不禁让我非常怀疑非配对领域的亮度增强，所以很疑惑，谢谢作者大佬的指点，祝您生活事业顺利，祉猷并茂！！！
