### ISSUE TITLE
鉴别器

### ISSUE THREAD

**Issue by bigbiglower** [langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement#32]
你好，我想问一下将trainer_seg_hist_fuse.py中from model.D_Net import Discriminator as D_Net中Discriminator改为contextDiscriminator后，model_D = D_Net().cuda()此行代码会报错。请问一下怎么解决？
![微信截图_20240603095518](https://github.com/langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement/assets/165480295/479d1c4b-bc29-4b17-a071-0e4065abfd37)

**Comment by langmanbusi** [comment]
contextDiscriminator实例化的时候需要这两个参数，要自己设定一下
