### ISSUE TITLE
train LLFlow_SKF

### ISSUE THREAD

**Issue by Nanncy99** [langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement#33]
Hello, I am very interested in your work. I would like to ask where the freezing of the semantic segmentation model is implemented, but I have not found it. We look forward to your reply.

**Comment by Boyyahui** [comment]
我也没有找见

**Comment by langmanbusi** [comment]
Please refer to 
https://github.com/langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement/blob/a2ade551508ecc7ea48f56ee5e49f023ea534c77/LLFlow_SKF/README.md?plain=1#L33
