### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by hlinqiao** [langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement#5]
Report missing file when reproducing code： default= './confs/LOL-pc.yml'

**Comment by langmanbusi** [comment]
![image](https://github.com/langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement/assets/89068081/86ef62f4-4d07-4425-909d-d76abd8e882b)
Here are the config files, you could choose one for experiments. "default" is just an example, you should manually set the configuration by yourself.
