### ISSUE TITLE
Miss file problem"hrnet_w48_pascal_context_cls59_480x480.pth"?

### ISSUE THREAD

**Issue by hlinqiao** [langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement#6]
I try to reproduce this code, I found the repo did not contain the pretrained file for hrnet.

**Comment by langmanbusi** [comment]
![image](https://github.com/langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement/assets/89068081/49f9bb33-4d6f-45b2-b426-3778616dbc09)
You can download the pre-trained file from here.

**Comment by hlinqiao** [comment]
Thank you very much.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月23日(星期二) 晚上10:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement] Miss file problem"hrnet_w48_pascal_context_cls59_480x480.pth"? (Issue #6)





 

 You can download the pre-trained file from here.
