### ISSUE TITLE
question about “Learning Semantic-Aware Knowledge Guidance for Low-Light Image Enhancement”

### ISSUE THREAD

**Issue by 43758726** [langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement#8]
Do you have pretrained model and config file which can using on testing the model with unpaired data?Thank you.

**Comment by DragonPengg** [comment]
我也想知道，有没有训练好的权重可以用来测试

**Comment by langmanbusi** [comment]
please check the readme files in subfolders.
we do not have pertrained model specially for unpaired data, just on LOL and LOLv2
