### ISSUE TITLE
请问下论文中提到的SEM在代码的哪里定义了？SAloss和SCHloss的代码在哪里

### ISSUE THREAD

**Issue by Zeng555** [langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement#9]
如题，论文中提到的SEM在哪里定义的？SAloss和SCHloss的代码在哪里找

**Comment by spec350** [comment]
就在loss文件下面https://github.com/langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement/blob/main/LLFlow_SKF/code/models/modules/loss.py

**Comment by Lantanoi** [comment]
我也找不到SEM，想问下你找到了吗

**Comment by Lantanoi** [comment]
> 就在loss文件下面https://github.com/langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement/blob/main/LLFlow_SKF/code/models/modules/loss.py

那SE模块的代码在哪里呢？
